export const categoriesCourses = [
  {
    id: 1,
    name: "Front End",
    color: "#6BD1FF",
    courses: [
      {
        id: 1,
        title: "Cuándo usar let, var y const?",
        category: "Front End",
        image: "./frontend-course_img1.jpg",
        video: "",
        description: "",
      },
      {
        id: 2,
        title: "¿Qué es JavaScript?",
        category: "Front End",
        image: "./frontend-course_img2.jpg",
        video: "",
        description: "",
      },
      {
        id: 3,
        title: "Equipo Frontend",
        category: "Front End",
        image: "./frontend-course_img3.jpg",
        video: "",
        description: "",
      },
    ],
  },
  {
    id: 2,
    name: "Back End",
    color: "#00C86F",
    courses: [
      {
        id: 4,
        title: "Spring Framework",
        category: "Back End",
        image: "./backend-course_img1.jpg",
        video: "",
        description: "",
      },
      {
        id: 5,
        title: "¿Qué es Sql y NoSql?",
        category: "Back End",
        image: "./backend-course_img2.jpg",
        video: "",
        description: "",
      },
      {
        id: 6,
        title: "Simplificando tu código en java, conoce los enum",
        category: "Back End",
        image: "./backend-course_img3.jpg",
        video: "",
        description: "",
      },
    ],
  },
  {
    id: 3,
    name: "Innovación y gestión",
    color: "#FFBA05",
    courses: [
      {
        id: 7,
        title: "¿Qué son las softskills?",
        category: "Innovación y gestión",
        image: "./innovation-course_img1.jpg",
        video: "",
        description: "",
      },
      {
        id: 8,
        title: "Las 7 softskills más deseadas",
        category: "Innovación y gestión",
        image: "./innovation-course_img2.jpg",
        video: "",
        description: "",
      },
      {
        id: 9,
        title: "Metodologias ágiles",
        category: "Innovación y gestión",
        image: "./innovation-course_img3.jpg",
        video: "",
        description: "",
      },
    ],
  },
];
